# Generated by Django 2.2.2 on 2019-06-18 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_drink_drinkrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='last_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='drinkrate',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Drink'),
        ),
    ]
