# Generated by Django 2.2.2 on 2019-06-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190618_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostPopularDrinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(default='non', max_length=100)),
                ('rate_count', models.IntegerField(null=True)),
                ('rate_sum', models.IntegerField(null=True)),
                ('rate_avarage', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='drinkrate',
            name='drink',
        ),
        migrations.AddField(
            model_name='drinkrate',
            name='drink_name',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AlterField(
            model_name='drinkrate',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
